name: Hello World Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 22f3000340@ds.study.iitm.ac.in
        run: |
          echo "Hello, World!"
          echo "This step contains the required email address"
          
      - name: Current Date
        run: date
        
      - name: List Files
        run: ls -la 